### PR TITLE
add an avg column

### LINKED ISSUE #4: Feature request: time per call
Add a column with (average) time per call in the output printing

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #4. Also fixes some bugs...

Please test @fredrikekre

### CODE REVIEW

**Comment by fredrikekre** [comment]
Very pretty!

**Comment by fredrikekre** [comment]
```
 ────────────────────────────────────────────────────────────────────────────
                                      Time                  Allocations      
                             ──────────────────────   ───────────────────────
      Tot / % measured:           2.84s / 12.2%           90.5MiB / 21.6%    

  Section            ncalls    time   %tot    avg      alloc   %tot     avg  
 ────────────────────────────────────────────────────────────────────────────
  μ: uⁱₛₜₐₜ               1    204ms  59.1%   204ms   3.40MiB  17.4%  3.40MiB
  M: assembling           9    124ms  35.8%  13.7ms   14.9MiB  76.0%  1.65MiB
    μ: solving        3.20k   2.72ms  0.79%   849ns   7.28MiB  37.2%  2.33KiB
  μ: Kuₐ = λMuₐ           1   16.9ms  4.90%  16.9ms    740KiB  3.69%   740KiB
  M: linear solve         4    476μs  0.14%   119μs    267KiB  1.33%  66.7KiB
  μ: assembling           1   99.0μs  0.03%  99.0μs    324KiB  1.62%   324KiB
  estimating error        5    719ns  0.00%   144ns        0B  0.00%     0.0B
 ────────────────────────────────────────────────────────────────────────────

```

**Comment by fredrikekre** [comment]
Perhaps the headlines should be right aligned actually? as `ncalls` is

**Comment by fredrikekre** [comment]
http://i.imgur.com/ZY8dKpA.gif

**Comment by KristofferC** [comment]
Yeah, I like that

**Comment by KristofferC** [comment]
Try now:

```
 ─────────────────────────────────────────────────────────────────────────────────
                                          Time                  Allocations      
                                 ──────────────────────   ───────────────────────
        Tot / % measured:             8.10s / 86.1%           5.31GiB / 85.0%    

  Section                ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────────────────
  assemble                    6    3.38s  48.4%   563ms   3.74GiB  82.9%   639MiB
    inner assemble         240k    2.30s  33.0%  9.58μs   3.14GiB  69.6%  13.7KiB
  linear solve                5    2.67s  38.3%   534ms    108MiB  2.34%  21.7MiB
  export                      1    482ms  6.91%   482ms   16.9MiB  0.37%  16.9MiB
  create sparse matrix        6    448ms  6.42%  74.7ms    663MiB  14.3%   111MiB
 ─────────────────────────────────────────────────────────────────────────────────
```

**Comment by fredrikekre** [comment]
Misalignment for the line under `Allocations`? Feels like that header should be one column to the right too.

**Comment by KristofferC** [comment]
How is it missaligned, there are 6 spaces to the left and right of the word "Allocations". You don't like that the top and bottom line sticks out one space further?

**Comment by fredrikekre** [comment]
> You don't like that the top and bottom line sticks out one space further?

That's what I meant. But idk...

**Comment by KristofferC** [comment]
I agree it looks a bit ugly looking at the top right corner

**Comment by KristofferC** [comment]
Should there perhaps be no sticking out to the left either then?

**Comment by fredrikekre** [comment]
Not sure what you mean, but perhaps the lines can be shortened?
```
 ─────────────────────────────────────────────────────────────────────────────────
                                          Time                  Allocations      
                                     ──────────────           ───────────────    
        Tot / % measured:             8.10s / 86.1%           5.31GiB / 85.0%    

  Section                ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────────────────
  assemble                    6    3.38s  48.4%   563ms   3.74GiB  82.9%   639MiB
    inner assemble         240k    2.30s  33.0%  9.58μs   3.14GiB  69.6%  13.7KiB
  linear solve                5    2.67s  38.3%   534ms    108MiB  2.34%  21.7MiB
  export                      1    482ms  6.91%   482ms   16.9MiB  0.37%  16.9MiB
  create sparse matrix        6    448ms  6.42%  74.7ms    663MiB  14.3%   111MiB
 ─────────────────────────────────────────────────────────────────────────────────
```

**Comment by fredrikekre** [comment]
Top line could also be shorter? 
```
    ───────────────────────────────────────────────────────────────────────────   
                                          Time                  Allocations      
                                     ──────────────           ───────────────    
        Tot / % measured:             8.10s / 86.1%           5.31GiB / 85.0%    

  Section                ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────────────────
  assemble                    6    3.38s  48.4%   563ms   3.74GiB  82.9%   639MiB
    inner assemble         240k    2.30s  33.0%  9.58μs   3.14GiB  69.6%  13.7KiB
  linear solve                5    2.67s  38.3%   534ms    108MiB  2.34%  21.7MiB
  export                      1    482ms  6.91%   482ms   16.9MiB  0.37%  16.9MiB
  create sparse matrix        6    448ms  6.42%  74.7ms    663MiB  14.3%   111MiB
 ─────────────────────────────────────────────────────────────────────────────────
```

**Comment by KristofferC** [comment]
```
 ───────────────────────────────────────────────────────────────────────────────
                                        Time                   Allocations
                                ──────────────────────   ───────────────────────
        Tot / % measured:            6.89s / 97.8%           5.20GiB / 85.0%

 Section                ncalls     time   %tot     avg     alloc   %tot      avg
 ───────────────────────────────────────────────────────────────────────────────
 assemble                    6    3.27s  48.6%   545ms   3.65GiB  82.7%   624MiB
   inner assemble         240k    1.92s  28.4%  7.98μs   3.14GiB  71.1%  13.7KiB
 linear solve                5    2.73s  40.5%   546ms    108MiB  2.39%  21.6MiB
 create sparse matrix        6    658ms  9.77%   110ms    662MiB  14.6%   110MiB
 export                      1   78.4ms  1.16%  78.4ms   13.1MiB  0.29%  13.1MiB
 ───────────────────────────────────────────────────────────────────────────────
```

now

**Pull request merged**
