### PR TITLE
add some precompile statements

### PR DESCRIPTION
**Pull request by ranocha**
Thanks for this nice package! This reduces the latency in some of my workload involving TimerOutputs.jl.

### CODE REVIEW

**Comment by ranocha** [comment]
Bump. Is there some interest in this?

**Comment by KristofferC** [comment]
Sorry missed this. Yeah, this seems useful!

**Comment by ranocha** [comment]
@KristofferC Would you mind making a new release of TimerOutputs.jl including this PR?

**Comment by KristofferC** [comment]
https://github.com/JuliaRegistries/General/pull/31117

**Pull request merged**
