### PR TITLE
add fast path and tweak some performance

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Thats great!

I get on master
```
  assemble                6    1.84s  45.7%  45.7%      396MiB  76.5%  76.5%
    inner assemble     240k    461ms  11.4%  11.4%          0B  0.00%  0.00%
```

and on this branch:

```
  assemble                6    1.41s  38.3%  38.3%      201MiB  62.4%  62.4%
    inner assemble     240k    435ms  11.8%  11.8%          0B  0.00%  0.00%
```

**Comment by KristofferC** [comment]
How long does `assemble` take if you remove the `inner assemble` timing completely?

**Comment by fredrikekre** [comment]
`  assemble               6    1.36s  34.2%  34.2%      201MiB  61.9%  61.9%`

**Comment by KristofferC** [comment]
So 0.05s overhead for 240k calls. Seems ok.

**Comment by fredrikekre** [comment]
Yes, and that has to be a very fast run, cause now i get around 1.4 seconds :p

**Comment by fredrikekre** [comment]
It might be possible to do something like https://github.com/timholy/ProgressMeter.jl/blob/master/src/ProgressMeter.jl#L164-L167 to remove timing from the lookup?

**Comment by KristofferC** [comment]
There is no delay from printing with this package and the time measured in a section should be very accurate: https://github.com/KristofferC/TimerOutputs.jl/blob/master/src/TimerOutput.jl#L113. The problem is with nested sections because the outer section just times a black box (which includes other sections).

**Comment by fredrikekre** [comment]
I didn't mean for printing, but rather remove time from the lookup. But now the overhead is very small anyway. If the time is taken after the lookup the timing for that section should be as good as possible, and I guess its hard to to something about the outer timers, so nvm my comment.

**Comment by KristofferC** [comment]
Travis doesn't seem to test anything ...

**Pull request merged**
